### ISSUE TITLE
comparisonSort/sampleSort Segmentation fault

### ISSUE THREAD

**Issue by pmandrik** [cmuparlay/pbbsbench#16]
Dear pbbsbench developers, in following dir `pbbsbench-master/benchmarks/comparisonSort/sampleSort` when run testInputs_small I have "TEST TERMINATED ABNORMALLY:" message.
Some debugs with gdb:
```
(gdb) run -r 1 -o /tmp/ofile189419_511475 ../../../testData/sequenceData/data/almostSortedSeq_10M_double
Starting program: /root/pmandrik/ptests/pbbsbench/pbbsbench-master/benchmarks/comparisonSort/sampleSort/sort -r 1 -o /tmp/ofile189419_511475 ../../../testData/sequenceData/data/almostSortedSeq_10M_double
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib64/libthread_db.so.1".
[New Thread 0x7fffed15f640 (LWP 3010650)]
[New Thread 0x7fffec95e640 (LWP 3010651)]
[New Thread 0x7fffec15d640 (LWP 3010652)]
[New Thread 0x7fffeb95c640 (LWP 3010653)]
<...>
sample: bucket id: 0.0090
sample: count sort: 0.0051
sample: bucket id: 0.0090
sample: count sort: 0.0050
sample: bucket id: 0.0101
sample: count sort: 0.0049
sample: bucket id: 0.0090
sample: count sort: 0.0048
sample: bucket id: 0.0089
sample: count sort: 0.0049
sample: bucket id: 0.0090
sample: count sort: 0.0050
sample: bucket id: 0.0089
sample: count sort: 0.0055
sample: bucket id: 0.0090
sample: count sort: 0.0047
Parlay time: 0.0254

[Thread 0x7fffd6131640 (LWP 3010696) exited]
<...>
[Thread 0x7fffed15f640 (LWP 3010650) exited]

Thread 1 "sort" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) backtrace
#0  0x0000000000000000 in ?? ()
#1  0x00000000004e6353 in std::thread::join() ()
#2  0x00000000004231e3 in parlay::scheduler<parlay::WorkStealingJob>::shutdown (this=0x68b680) at ./parlay/scheduler.h:289
#3  parlay::scheduler<parlay::WorkStealingJob>::~scheduler (this=0x68b680, __in_chrg=<optimized out>) at ./parlay/scheduler.h:93
#4  std::default_delete<parlay::scheduler<parlay::WorkStealingJob> >::operator() (this=<optimized out>, __ptr=0x68b680) at /usr/include/c++/10.3.1/bits/unique_ptr.h:85
#5  std::default_delete<parlay::scheduler<parlay::WorkStealingJob> >::operator() (__ptr=0x68b680, this=<optimized out>) at /usr/include/c++/10.3.1/bits/unique_ptr.h:79
#6  std::unique_ptr<parlay::scheduler<parlay::WorkStealingJob>, std::default_delete<parlay::scheduler<parlay::WorkStealingJob> > >::~unique_ptr (this=<optimized out>, __in_chrg=<optimized out>)
    at /usr/include/c++/10.3.1/bits/unique_ptr.h:361
#7  parlay::fork_join_scheduler::~fork_join_scheduler (this=<optimized out>, __in_chrg=<optimized out>) at ./parlay/scheduler.h:297
#8  0x000000000052a7f9 in __run_exit_handlers ()
#9  0x000000000052a950 in exit ()
#10 0x0000000000516ce1 in __libc_start_call_main ()
#11 0x00000000005180cf in __libc_start_main_impl ()
#12 0x0000000000406a95 in _start ()
```
pointing to parlay lib.

OS: Linux 5.10.0-60.18.0.50.h896.eulerosv2r11.x86_64
gcc: 10.3.1 (GCC)
parlay: the one available today at github

Best regards, Petr

**Comment by gblelloch** [comment]
closing old issues.   seems to be ok now.    some updates were being made to the parlay scheduler that might have caused this issue.
